title: Abhishaike Mahajan
author:
  name: Abhishaike Mahajan
  email: abhishaike@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Blog for Abhishaike Mahajan

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    email: abhishaike@gmail.com
    github: Abhishaike
    instagram: abuuty.art
    twitter: abuutyshake
    google-scholar: fSyeqzAAAAAJ


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

# Google Analytics
google_analytics: G-GL4EMF8MM7

plugins:
 - jekyll-feed
 - jekyll-seo-tag
